import "./globals.css";

export const metadata = {
  title: "JK // DEV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-800 flex items-center justify-center h-screen w-full">
        {children}
      </body>
    </html>
  );
}
